added all files
olawalecoder/Hello-Microverse pull request #1
Opened 2021-11-23 14:46 UTC by olawalecoder

Use for learning linters

2021-11-23 15:47 UTC, alonsofl requested changes
Hi @olawalecoder,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] I would suggest updating the PR title and description to give more information about the changes introduced in the PR (e.g., Setup project, Add index with a stylesheet and linters). Remember that in a remote workflow we have to deal with timezones and giving the most information possible could help us with delays when asking for more information :pushpin: :wink:

_Check the comments under the review._

## To highlight :dart:
- Linters working properly :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing the first letter of the commit messages and use imperative (e.g., use "Fix bug" instead of "Fixed bug") for better practices :hugs:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 15:47 UTC, alonsofl commented on .gitignore
> +test.md
- [ ] You have done an excellent job with your project but I would suggest also ignoring the `node_modules` folder for better practices because sometimes by mistake it could be uploaded and it is not necessary (also, it is a really huge folder :sweat_smile:). You could find how to ignore the `node_modules` folder [here](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/) :wink:

2021-11-23 15:47 UTC, alonsofl commented on test.md
> +This file should be ignored by git
- [ ] There is an issue with this file because it was ignored and it is not supposed to be in the PR. I think the problem is because you tracked it (when making a commit) before ignoring it. You could [try this solution to clean the cache](https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign) :pushpin: :smiley:

2021-11-23 15:47 UTC, alonsofl commented on index.html
> +    <link rel="stylesheet" href="/style.css">
- [ ] There is an issue with your stylesheet because the `<h1>` is being shown with the default color. I think the problem is because you are using the `/` before the path, you could remove the `/` or even better add a `.` before so it look like this: `./style.css` :wink:
![image](https://user-images.githubusercontent.com/81522435/143056056-79910401-7138-4b8a-95c6-1aa79afc470a.png)
![image](https://user-images.githubusercontent.com/81522435/143056089-22498d6e-8e0a-47a4-afc8-2bd8c90cf7b6.png)

2021-11-24 07:15 UTC, olawalecoder commented on index.html
> +    <link rel="stylesheet" href="/style.css">
Thank you. I have corrected that.

2021-11-24 07:27 UTC, olawalecoder commented on .gitignore
> +test.md
Thanks for the review

2021-11-24 07:54 UTC, olawalecoder commented on index.html
> +    <link rel="stylesheet" href="/style.css">
Corrected. Thanks

2021-11-24 07:59 UTC, ShoiraTa approved these changes
## Status: Approved :heavy_check_mark:

Hi @olawalecoder ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 

***
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 08:36 UTC, merged